apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
  namespace: karpenter  # Added namespace
spec:
  requirements:
    - key: "karpenter.k8s.aws/instance-family"
      operator: In
      values: ["t3", "m5", "c5"]
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64", "arm64"]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot", "on-demand"]
  providerRef:
    name: default
  limits:
    resources:
      cpu: "1000"
      memory: "1000Gi"
  consolidation:
    enabled: true